---
# Copy this file to config.yml, then amend the settings below according to
# your system configuration.

sdk_path: $ANDROID_HOME

repo_icon: meshtastic_icon.png

repo_keyalias: fv-az341-931.xez1knj354qubb1hnut5jnrmef.gx.internal.cloudapp.net
keystore: keystore.p12
keystorepass: IqcP++zKO05gH/rWbAJuz3tkRKHSTfMpHSgke4LAHAk=
keypass: IqcP++zKO05gH/rWbAJuz3tkRKHSTfMpHSgke4LAHAk=
keydname: CN=fv-az341-931.xez1knj354qubb1hnut5jnrmef.gx.internal.cloudapp.net, OU=F-Droid
