name: fdroid update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install fdroid server
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt-get -qy install fdroidserver --no-install-recommends

#      - name: Load secrets
#        run: |
#          mkdir fdroid
#          echo $fdroid_config | base64 -di > ./fdroid/config.yml
#          echo $fdroid_keystore | base64 -di > ./fdroid/keystore.p12
#          chmod 600 ./fdroid/config.yml ./fdroid/keystore.p12
#        env:
#          fdroid_config: ${{ secrets.fdroid_config }}
#          fdroid_keystore: ${{ secrets.fdroid_keystore }}

      - name: Run fdroid init
        run: fdroid init
